/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeoForAstrologersRouteImport } from './routes/seo-for-astrologers'
import { Route as MarketingForTarotReadersRouteImport } from './routes/marketing-for-tarot-readers'
import { Route as MarketingForNumerologistsRouteImport } from './routes/marketing-for-numerologists'
import { Route as InstagramMarketingForAstrologersRouteImport } from './routes/instagram-marketing-for-astrologers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoForAstrologersRoute = SeoForAstrologersRouteImport.update({
  id: '/seo-for-astrologers',
  path: '/seo-for-astrologers',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingForTarotReadersRoute =
  MarketingForTarotReadersRouteImport.update({
    id: '/marketing-for-tarot-readers',
    path: '/marketing-for-tarot-readers',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketingForNumerologistsRoute =
  MarketingForNumerologistsRouteImport.update({
    id: '/marketing-for-numerologists',
    path: '/marketing-for-numerologists',
    getParentRoute: () => rootRouteImport,
  } as any)
const InstagramMarketingForAstrologersRoute =
  InstagramMarketingForAstrologersRouteImport.update({
    id: '/instagram-marketing-for-astrologers',
    path: '/instagram-marketing-for-astrologers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/instagram-marketing-for-astrologers': typeof InstagramMarketingForAstrologersRoute
  '/marketing-for-numerologists': typeof MarketingForNumerologistsRoute
  '/marketing-for-tarot-readers': typeof MarketingForTarotReadersRoute
  '/seo-for-astrologers': typeof SeoForAstrologersRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/instagram-marketing-for-astrologers': typeof InstagramMarketingForAstrologersRoute
  '/marketing-for-numerologists': typeof MarketingForNumerologistsRoute
  '/marketing-for-tarot-readers': typeof MarketingForTarotReadersRoute
  '/seo-for-astrologers': typeof SeoForAstrologersRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/instagram-marketing-for-astrologers': typeof InstagramMarketingForAstrologersRoute
  '/marketing-for-numerologists': typeof MarketingForNumerologistsRoute
  '/marketing-for-tarot-readers': typeof MarketingForTarotReadersRoute
  '/seo-for-astrologers': typeof SeoForAstrologersRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/instagram-marketing-for-astrologers'
    | '/marketing-for-numerologists'
    | '/marketing-for-tarot-readers'
    | '/seo-for-astrologers'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/instagram-marketing-for-astrologers'
    | '/marketing-for-numerologists'
    | '/marketing-for-tarot-readers'
    | '/seo-for-astrologers'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/instagram-marketing-for-astrologers'
    | '/marketing-for-numerologists'
    | '/marketing-for-tarot-readers'
    | '/seo-for-astrologers'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  InstagramMarketingForAstrologersRoute: typeof InstagramMarketingForAstrologersRoute
  MarketingForNumerologistsRoute: typeof MarketingForNumerologistsRoute
  MarketingForTarotReadersRoute: typeof MarketingForTarotReadersRoute
  SeoForAstrologersRoute: typeof SeoForAstrologersRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-for-astrologers': {
      id: '/seo-for-astrologers'
      path: '/seo-for-astrologers'
      fullPath: '/seo-for-astrologers'
      preLoaderRoute: typeof SeoForAstrologersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-for-tarot-readers': {
      id: '/marketing-for-tarot-readers'
      path: '/marketing-for-tarot-readers'
      fullPath: '/marketing-for-tarot-readers'
      preLoaderRoute: typeof MarketingForTarotReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing-for-numerologists': {
      id: '/marketing-for-numerologists'
      path: '/marketing-for-numerologists'
      fullPath: '/marketing-for-numerologists'
      preLoaderRoute: typeof MarketingForNumerologistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-marketing-for-astrologers': {
      id: '/instagram-marketing-for-astrologers'
      path: '/instagram-marketing-for-astrologers'
      fullPath: '/instagram-marketing-for-astrologers'
      preLoaderRoute: typeof InstagramMarketingForAstrologersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  InstagramMarketingForAstrologersRoute: InstagramMarketingForAstrologersRoute,
  MarketingForNumerologistsRoute: MarketingForNumerologistsRoute,
  MarketingForTarotReadersRoute: MarketingForTarotReadersRoute,
  SeoForAstrologersRoute: SeoForAstrologersRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
